import type { Metadata } from "next";
import "./ui/globals.css";
import ScrollSaver from "./componentes/scroll-saver";
import FontPreloader from "./componentes/font-preloader";



export const metadata: Metadata = {
  title: "fulladminaccess",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        <FontPreloader/>
      </head>
      <body className="h-max flex flex-col font-satoshi">
        <ScrollSaver/>
        {children}
      </body>
    </html>
  );
}

